{
 "title": "Dashboard Wellington",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Medição de Temperatura - Wellington Weikamp Porto",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datahorautc AS \"time\",\n  valor\nFROM publicacoes\nWHERE\n  $__timeFilter(datahora) AND origem=\"Wellington\" AND (descricao = 'Temperatura' AND origem = 'Wellington')\nORDER BY datahorautc"
    }
   ]
  },
  {
   "title": "Medição de Temperatura - Últimos Valores",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "sensoriamento",
     "rawSql": "SELECT datahorautc, valor FROM sensoriamento.publicacoes WHERE (descricao = 'Temperatura' AND origem = 'Wellington') ORDER BY datahorautc DESC LIMIT 6 "
    }
   ]
  },
  {
   "title": "Medição de Umidade - Wellington Weikamp Porto",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datahorautc AS \"time\",\n  valor\nFROM publicacoes\nWHERE\n  $__timeFilter(datahora) AND (descricao = 'Umidade' AND origem = 'Wellington')\nORDER BY datahorautc"
    }
   ]
  },
  {
   "title": "Medição de Umidade - Últimos Valores",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "sensoriamento",
     "rawSql": "SELECT datahorautc, valor FROM sensoriamento.publicacoes WHERE (descricao = 'Umidade' AND origem = 'Wellington') ORDER BY datahorautc DESC LIMIT 6 "
    }
   ]
  },
  {
   "title": "Histograma últimas medições",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND (descricao = 'Temperatura' AND origem = 'Wellington')\r\n  AND DATE_SUB(CURDATE(), INTERVAL 7 DAY)\r\n  ORDER BY datahorautc LIMIT 500"
    }
   ]
  },
  {
   "title": "Comparação da temperatura máxima por mês",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(valor) AS max_temp,\r\n  MONTHNAME(datahorautc) AS month,\r\n  origem\r\nFROM \r\n  publicacoes\r\nWHERE\r\n   descricao = 'Temperatura' AND YEAR(datahorautc) = YEAR(NOW())\r\nGROUP BY origem, month\r\nORDER BY month DESC"
    }
   ]
  },
  {
   "title": "Comparação da temperatura mínima por mês",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MIN(valor) AS min_temp,\r\n  MONTHNAME(datahorautc) AS month,\r\n  origem\r\nFROM \r\n  publicacoes\r\nWHERE\r\n   descricao = 'Temperatura' AND YEAR(datahorautc) = YEAR(NOW())\r\nGROUP BY origem, month\r\nORDER BY month DESC"
    }
   ]
  },
  {
   "title": "Comparação temperatura colegas",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor AS Wellington\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND origem=\"Wellington\" AND descricao=\"Temperatura\"\r\nORDER BY datahorautc"
    },
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor AS Gilson\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND origem=\"Gilson\" AND descricao=\"Temperatura\"\r\nORDER BY datahorautc"
    },
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor AS Graciela\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND origem=\"Graciela\" AND descricao=\"Temperatura\"\r\nORDER BY datahorautc"
    },
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor AS Tiago\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND origem=\"Tiago\" AND descricao=\"Temperatura\"\r\nORDER BY datahorautc"
    },
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor AS Karen\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND origem=\"Karen\" AND descricao=\"Temperatura\"\r\nORDER BY datahorautc"
    }
   ]
  },
  {
   "title": "Comparação umidade colegas",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor AS Wellington\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND origem=\"Wellington\" AND descricao=\"Umidade\"\r\nORDER BY datahorautc"
    },
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor AS Gilson\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND origem=\"Gilson\" AND descricao=\"Umidade\"\r\nORDER BY datahorautc"
    },
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor AS Graciela\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND origem=\"Graciela\" AND descricao=\"Umidade\"\r\nORDER BY datahorautc"
    },
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor AS Tiago\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND origem=\"Tiago\" AND descricao=\"Umidade\"\r\nORDER BY datahorautc"
    },
    {
     "rawSql": "SELECT\r\n  datahorautc AS \"time\",\r\n  valor AS Karen\r\nFROM publicacoes\r\nWHERE\r\n  $__timeFilter(datahora) AND origem=\"Karen\" AND descricao=\"Umidade\"\r\nORDER BY datahorautc"
    }
   ]
  }
 ]
}